spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://tracing-service:8080

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    estoqueservice: /estoque/**
    pedidoservice: /pedido/**
  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    estoqueservice:
      execution.isolation.thread.timeoutInMilliseconds: 5000
    pedidoservice:
      execution.isolation.thread.timeoutInMilliseconds: 3000
