spring:
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://database:3306/db_srm_estoque?characterEncoding=utf8'
    username: 'srm'
    password: '{cipher}134a95195b7c790953589eb1931e5738922dff593506d028a42d3824486889f5'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'
  jpa:
    hibernate:
      ddl-auto: 'none'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
        show_sql: 'true'
        format_sql: 'true'

flyway:
  baseline-version: 1
  check-location: 'true'
  enabled: 'true'
  locations: 'classpath:db/migration'
  sql-migration-prefix: 'V'
  sql-migration-separator: '_'
  sql-migration-suffix: '.sql'
  url: 'jdbc:mysql://database:3306/db_srm_estoque?characterEncoding=utf8'
  consumer: 'srm'
  password: '{cipher}134a95195b7c790953589eb1931e5738922dff593506d028a42d3824486889f5'

srm:
  message:
    fail: 'Quantidade não está disponível no estoque! ehhhhhh'

signing:
  key: '44354_gj35vh*ags'

keycloak:
  auth-server-url: http://172.32.0.113:8080/auth
  realm: srm
  ssl-required: none
  resource: srm-ecommerce
  autodetect-bearer-only: true
  credentials:
    secret: 27409db6-0707-4dc4-9e11-86cc6a1869de
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: "/v1/products/*"
